etl:
  utils:
    table_creation: |
      CREATE TABLE {table_name} ({table_content});
    table_deletion: |
      DROP TABLE {table_name};
    table_content_extraction: |
      SELECT * from {table_name};

  role: |
    You are an SQL expert. Your task is to create an SQL query that extracts and aggregates data from a given set of SQL tables, and inserts the result into a target fact table.

    You are working in the syntax of the {sql_context}.

    Here are the source tables:
    {tables_schema}

    Here is the target fact table where the data should be inserted:
    {generated_fact_table}

    Please write only the SQL query to perform the necessary ETL operation (INSERT INTO ... SELECT ...). Do not include any explanation or additional text. Assume the necessary joins and aggregations based on the schema structure.
  prompt: |
    You are an SQL expert. Your task is to generate INSERT query for 3 elements. Don't forget, that if one table contains a reference to another table, then referenced table should contain a desired value ahead of its insertion into referencing table. You are provided with the following schemas: {table_schemas}
    Please output only the SQL queries, there is no need to output the explanation or something else.