model:
  prompts: 
    role: |
      You are an SQL expert.

      Your task is to generate an SQL query to create a fact table in a star schema.

      You are provided with the following tables' schemas:

    tables: |
      {tables}

    operations: |
      Include fields that compute the following operations: {operations}

    time_aggregation: |
      The fact table should also include time-based aggregation.
      This aggregation should be done over the field {date_field}, and the {time} component should be extracted.
      The generated field for this purpose should be of name {generated_time_name} and of type int.

    user_prompt: |
      Ensure that the fact table satisfies the following requirements:
      {requirements}

    remarks_one_aggregation: |
      - The fact table must contain a primary key.
      - Do not create a unique primary key that is not part of the provided table schemas.
      - The primary key must not be auto-incremented.
      - Ensure that the primary key is: {primary_key}.
      - Foreign keys must reference the related dimension tables appropriately.
      - The output must contain only the SQL query that creates the fact table.
      - Do not repeat the prompt or provide any explanations.

    remarks_multiple_aggregation: |
      - The fact table must contain a primary key.
      - Do not create a unique primary key that is not part of the provided table schemas.
      - The primary key must not be auto-incremented.
      - Ensure that the primary key is a composite key: ({key}).
      - Foreign keys must reference the related dimension tables appropriately.
      - The output must contain only the SQL query that creates the fact table.
      - Do not repeat the prompt or provide any explanations.

    checking_prompt: |
      Given the user input: {user_prompt}, please identify whether the next generated fact table is correct: {fact_table}.
      Make sure that if time aggregation is asked, then generated fact table doesn't have a foreign key indicating time that references to any other table.
      Query should not contain any insert, select, and other key words. It should be the "create table" query with only the definition of the table schema.
      If generated table satisfies the generated prompt, then output just "Yes". However, if there is an exception, then please outputs the list of required changes.
    
    fixing_prompt: |
      Your task is to fix the SQL query for the creation of the fact table.
      Given that the user has asked: {user_prompt}, and the following feedback:
      {feedback}.
      Please fix the next query: 
      {fact_table}
      The output should be the "create table" query that only defines the table's schema.

